version: '3.1'

services:
  db:
    image: postgres
    container_name: bookstore-db
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: bookstore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
